version: '2'

services:

    django:
        build: .
        ports:
            - 8000:8000
            - 8001:8001
        # command: python manage.py runserver 0.0.0.0:8001
        # command: bash
        command: ls
        volumes:
            - .:/app
        tty: true
        stdin_open: true



