# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_div'),
    ]

    operations = [
        migrations.AddField(
            model_name='div',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='/media/slim'),
        ),
    ]
