# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_div_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='div',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Website'),
        ),
        migrations.AlterField(
            model_name='div',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
