# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20170323_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='sequence_no',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
