# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_page_sequence_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='div',
            name='sequence_no',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
