# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_div_sequence_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='div',
            name='sequence_no',
            field=models.PositiveSmallIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='page',
            name='sequence_no',
            field=models.PositiveSmallIntegerField(default=1000),
        ),
    ]
