# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_auto_20170417_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
