# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='theme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.Theme'),
            preserve_default=False,
        ),
    ]
