# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 06:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_auto_20170418_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='div1',
        ),
        migrations.RemoveField(
            model_name='website',
            name='div10',
        ),
        migrations.RemoveField(
            model_name='website',
            name='div2',
        ),
        migrations.RemoveField(
            model_name='website',
            name='div3',
        ),
        migrations.RemoveField(
            model_name='website',
            name='div4',
        ),
        migrations.RemoveField(
            model_name='website',
            name='div5',
        ),
        migrations.RemoveField(
            model_name='website',
            name='div6',
        ),
        migrations.RemoveField(
            model_name='website',
            name='div7',
        ),
        migrations.RemoveField(
            model_name='website',
            name='div8',
        ),
        migrations.RemoveField(
            model_name='website',
            name='div9',
        ),
    ]
