# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_auto_20170418_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='div1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='div1', to='common.Div'),
        ),
        migrations.AddField(
            model_name='theme',
            name='div10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='div10', to='common.Div'),
        ),
        migrations.AddField(
            model_name='theme',
            name='div2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='div2', to='common.Div'),
        ),
        migrations.AddField(
            model_name='theme',
            name='div3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='div3', to='common.Div'),
        ),
        migrations.AddField(
            model_name='theme',
            name='div4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='div4', to='common.Div'),
        ),
        migrations.AddField(
            model_name='theme',
            name='div5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='div5', to='common.Div'),
        ),
        migrations.AddField(
            model_name='theme',
            name='div6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='div6', to='common.Div'),
        ),
        migrations.AddField(
            model_name='theme',
            name='div7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='div7', to='common.Div'),
        ),
        migrations.AddField(
            model_name='theme',
            name='div8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='div8', to='common.Div'),
        ),
        migrations.AddField(
            model_name='theme',
            name='div9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='div9', to='common.Div'),
        ),
    ]
