# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_auto_20170418_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='div1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='w_div1', to='common.Div'),
        ),
        migrations.AddField(
            model_name='website',
            name='div10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='w_div10', to='common.Div'),
        ),
        migrations.AddField(
            model_name='website',
            name='div2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='w_div2', to='common.Div'),
        ),
        migrations.AddField(
            model_name='website',
            name='div3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='w_div3', to='common.Div'),
        ),
        migrations.AddField(
            model_name='website',
            name='div4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='w_div4', to='common.Div'),
        ),
        migrations.AddField(
            model_name='website',
            name='div5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='w_div5', to='common.Div'),
        ),
        migrations.AddField(
            model_name='website',
            name='div6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='w_div6', to='common.Div'),
        ),
        migrations.AddField(
            model_name='website',
            name='div7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='w_div7', to='common.Div'),
        ),
        migrations.AddField(
            model_name='website',
            name='div8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='w_div8', to='common.Div'),
        ),
        migrations.AddField(
            model_name='website',
            name='div9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='w_div9', to='common.Div'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='div1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_div1', to='common.Div'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='div10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_div10', to='common.Div'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='div2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_div2', to='common.Div'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='div3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_div3', to='common.Div'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='div4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_div4', to='common.Div'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='div5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_div5', to='common.Div'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='div6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_div6', to='common.Div'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='div7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_div7', to='common.Div'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='div8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_div8', to='common.Div'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='div9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_div9', to='common.Div'),
        ),
    ]
