# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('themes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cards.Themes')),
                ('url', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Select Status of the Card: ', max_length=20)),
            ],
            bases=('cards.themes',),
        ),
    ]
