# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], help_text='Select Status of the Card: ', max_length=20),
        ),
    ]
