# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20170207_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='url',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
