# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20170207_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='themes',
            name='is_theme',
            field=models.BooleanField(default=False),
        ),
    ]
