# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_themes_theme_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themes',
            name='div1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='themes',
            name='div2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='themes',
            name='div3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='themes',
            name='div4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='themes',
            name='div5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
